name: reunionou
description: organise et participe à des réunions avec tes amis !

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  flutter_native_splash: ^2.2.18
  google_fonts: ^4.0.3
  flutter_datetime_picker: ^1.5.1
  faker: ^2.1.0
  uuid: ^3.0.7
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
  image_path: "./assets/images/reunionouIconOpaque.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#e278ff"
  image: "./assets/images/reunionouSplash.png"
  android: true
  ios: true
  web: false
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/reunionouIconOpaque.png
    - assets/images/reunionouIcon.png
    - assets/images/reunionouSplash.png
    - assets/.env
  fonts:
    - family: SairaCondensed
      fonts:
        - asset: assets/fonts/SairaCondensed-Regular.ttf
    - family: SairaCondensedBold
      fonts:
        - asset: assets/fonts/SairaCondensed-Bold.ttf
