DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
    `id` UUID PRIMARY KEY UNIQUE,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `name` VARCHAR(255) NOT NULL,
    `pass` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;